### ISSUE TITLE
participants should be able to be both data consumers and data providers in a market

### ISSUE THREAD

**Issue by goeddea** [crossbario/xbr-protocol#12]
Participants should be able to be both data consumer and data provider in a single market.

This is a central part of the data value chains we champion: A participant consumes data in a market and provides insight based on this - in the same market.

It is also something that we explicitly mention throughout the whitepaper.

**Comment by oberstet** [comment]
Ok, yes, agreed! I'll try to get there quick, but this triggers some deeper changes (read: takes some days).

---

However, we need to define another relation rgd delegates.

IMO it should be:

1. a given account ("Alice") can be (after registering in the XBR Network) a XBR Provider and/or Consumer in zero or more markets
2. a XBR provider or consumer delegate (or a XBR market maker which effectively is the delegate for a market) can only be one of these, and attached to one market
