### ISSUE TITLE
Complete payment channel closing

### ISSUE THREAD

**Issue by oberstet** [crossbario/xbr-protocol#25]

**Comment by oberstet** [comment]
![Bildschirmfoto von 2019-08-29 21-44-19](https://user-images.githubusercontent.com/233340/63971221-4b680180-caa6-11e9-88dd-1e8b1c38bd4b.png)

**Comment by om26er** [comment]
\o/

**Comment by oberstet** [comment]
fixed (mostly) via https://github.com/crossbario/xbr-protocol/pull/43 and the respective changes in crossbarfx. what is missing is reactivating signature checking after the regression in signature deviation between py/js and solidity
