### ISSUE TITLE
Cross-language buyer-seller test

### ISSUE THREAD

**Issue by oberstet** [crossbario/xbr-protocol#27]
Add a CI run test (to be run in the repo here) with:

* [ ] Data market: ganache, a crossbarfx master node and an edge node with market maker
* [x] ABPy based buyer
* [x] ABPy based seller
* [x] ABJS based buyer
* [x] ABJS based seller
* [x] ABJ based buyer
* [x] ABJ based seller

**Comment by om26er** [comment]
This is kind of dependent on https://github.com/crossbario/crossbarfx/issues/325, if you are working on it already (as seen on the project board), I can in the meantime look to enhance the java XBR implementation (which is still lagging).

**Comment by om26er** [comment]
dependent i.e. so that we don't end up duplicating the effort.

**Comment by oberstet** [comment]
see: https://github.com/crossbario/dsq-examples/tree/master/examples

**Comment by oberstet** [comment]
JS examples:

• https://github.com/crossbario/dsq-examples/blob/master/examples/js/buyer.js
• https://github.com/crossbario/dsq-examples/blob/master/examples/js/seller.js

PS examples:

* https://github.com/crossbario/dsq-examples/blob/master/examples/python/buyer.py
* https://github.com/crossbario/dsq-examples/blob/master/examples/python/seller.py

---
