### ISSUE TITLE
XBR EULA

### ISSUE THREAD

**Issue by oberstet** [crossbario/xbr-protocol#40]
All XBR network members must accept our XBR EULA when registering:

* https://github.com/crossbario/xbr-protocol/blob/master/contracts/XBRNetwork.sol#L270

The EULA must be stored on IPFS .. as a ZIP file containing:

```
oberstet@thinkpad-x1:~/scm/crossbario/xbr-protocol$ ipfs cat QmU7Gizbre17x6V2VR1Q2GJEjz6m8S1bXmBtVxS2vmvb81 > /tmp/eula.zip
(cpy373_1) oberstet@thinkpad-x1:~/scm/crossbario/xbr-protocol$ unzip /tmp/eula.zip 
Archive:  /tmp/eula.zip
   creating: xbr-eula/
  inflating: xbr-eula/README.txt     
  inflating: xbr-eula/XBR-EULA.txt   
  inflating: xbr-eula/COPYRIGHT.txt  
```

**Comment by goeddea** [comment]
For the testnet release I suggest the following:

These contracts are deployed by Crossbar.io GmbH of Erlangen, Germany ("Crossbar.io"). They are inteded for testing purposes only and Crossbario.io makes no warranties regarding any functionality or fitness for purpose.

This EULA grants you a license to use these contracts for testing the XBR technology stack developed by Crossbar.io. This does not cover usage which may endanger the health or lives of people. Usage is at you own risk.

By agreeing to this EULA, you accept that the following IP is held by Crossbar.io:
   - the Crossbar.io, WAMP and XBR trademarks, and
   - the copyright in Crossbar.io, Crossbar.io FX, including the XBR market maker functionality, and the 
XBR smart contracts.

Should you as a current licensed user sue Crossbar.io in connection with the above IP, then this license is automatically revoked.

**Comment by oberstet** [comment]
fixed via https://github.com/crossbario/xbr-protocol/pull/49
