### ISSUE TITLE
security/no-block-members: Avoid using 'block.timestamp'.

### ISSUE THREAD

**Issue by albertxos** [crossbario/xbr-protocol#41]
https://github.com/crossbario/xbr-protocol/blob/5c8fcb0a73e68a3ffa4da93ff051f58224fbf199/contracts/XBRNetwork.sol#L205

**Comment by oberstet** [comment]
yes, I'm aware of that warning: the way we use `block.timestamp` is purely informational (it is not used in any crypto stuff or such), and hence the warning can be ignored safely
