### ISSUE TITLE
Evaluate alternative token standards

### ISSUE THREAD

**Issue by goeddea** [crossbario/xbr-protocol#6]
We want to use  a token standard that is widespread and accepted in the market - which at the moment is ERC20.

At the same time, newer token standards may provide features that we need/can use to make our life easier.

Candidates for evaluation:

- ERC223 - https://github.com/ethereum/EIPs/issues/223
- ERC777 - https://github.com/ethereum/eips/issues/777 - this has authorization for "operators" which can update token balances

**Comment by oberstet** [comment]
see https://github.com/PhABC/ethereum-token-standards-list/blob/master/README.md for a bigger list.

because of #22, ERC-865 and ERC-965 are of particular interest.

**Comment by oberstet** [comment]
Right now, we are using the standard/battle-tested openzeppelin erc20 token implementation (https://github.com/crossbario/xbr-protocol/blob/master/contracts/XBRToken.sol).

I don't think the additional features of alternative tokens justify the risks and hassles of migrating - at least for now. closing: won't fix (at this point)

**Comment by oberstet** [comment]
so rgd the token used in markets: we have redesigned this, and now allow any ERC20 token as a means of payment when creating the market https://xbr.network/docs/protocol/api/index.html#createmarket

consequently, this issue is kinda void

**Comment by oberstet** [comment]
> consequently, this issue is kinda void

it is, for market coins, but not the xbr network token

---

https://www.cointelligence.com/content/comparison-erc20-erc223-new-ethereum-erc777-token-standard/

**Comment by oberstet** [comment]
we now have market specific coins
